### ISSUE TITLE
Request to change package type

### ISSUE THREAD

**Issue by Robin-w151** [unlocomqx/svelte-reduxify#2]
When importing the `index.js` from a node application I get the following warning:
`(node:1934567) Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension.`

Would it be possible to add `type='module'` to the `package.json`?

**Comment by unlocomqx** [comment]
Hi @Robin-w151 👋 

Please check version 1.4.0 that I just published and see if the warning is gone

Cheers

**Comment by Robin-w151** [comment]
Hi @unlocomqx 

The build works now just fine. Thank you for your quick fix!

**Comment by unlocomqx** [comment]
You're welcome bro
